### ISSUE TITLE
Need to reduce generation time ...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#210]
```
All,



We currently generate netTiers over a fairly large table set (several
hundred).  The generation is starting to take a substantial amount of time
and machine resources.

My question is; is it possible, and is there a tool that will allow us to
only generate what has changed?  If I could simply regen based on the
"diff" between current change set and last change set, we would be much
MUCH more agile.

Any information or help is appreciated.


-mick


```

Original issue reported on code.google.com by `mick.c...@gmail.com` on 7 May 2009 at 2:58

**Comment by jeremeguenther** [comment]
Are you sure the speed issues are due to the generation?  Typically the biggest speed issue is due to .netTiers executing every custom sproc with all null parameters so it can analyze the result set.  The best way to speed this up is to add a check to your longer running custom sprocs for this null state and return whatever you want nettiers to analyze rather than actually running the sproc.
