### ISSUE TITLE
Date Format 

### ISSUE THREAD

**Issue by aahameed** [netTiers/netTiers#456]
i had really bad problem with date format  in Getpaged  and all searching functions all my tries fail to add date in where-clause with date format  d m y 

this my code 

` DataRepository.PerTrVacationProvider.GetPaged(string.Format(" ((DATEADD(DD,0,DATEDIFF(DD,0,'{0}')) between DATEADD(DD,0,DATEDIFF(DD,0,FromDate)) and DATEADD(DD,0,DATEDIFF(DD,0,ToDate)) ) or ( DATEADD(DD,0,DATEDIFF(DD,0,'{1}')) between DATEADD(DD,0,DATEDIFF(DD,0,FromDate))  and DATEADD(DD,0,DATEDIFF(DD,0,toDate)) )) and EmployeeID = {2} ",Vacation.FromDate.Value.ToString("dd/MM/yyyy"), Vacation.ToDate.Value.ToString("dd/MM/yyyy"), Vacation.EmployeeId),"", 0, 10, out TotalCount);
`

and the date format was set to mdy and never changed and when i tried to change the stored procedure to add  `set dateformat dmy`  i found that netTires never see the changes i already made in the stored and still get the body of the original stored procedure 

i have work around  and do this 
```
DateTime dt = Convert.ToDateTime(row["CheckInOut"].ToString());
                            string filterDate = string.Format("{0}{1}{2}", dt.Year + "", dt.Month.ToString().PadLeft(2, '0'), dt.Day.ToString().PadLeft(2, '0'));
                            int result;
                            int? shiftId = DataRepository.Provider.PerDefShiftDetailProvider.GetPaged(string.Format("EmployeeID={0} AND CONVERT(VARCHAR(20), ShiftDate , 112) = '{0}'", Employee[0].Id, filterDate), "", 0, 100, out result)[0].ShiftId;

```
but why i can't set the date format either in the getpaged function  or in the stored procedure   

i am using netTiers2.3.0 b1 and code smith 7.1

**Comment by jeremeguenther** [comment]
I believe the issue is that you are trying to use the whereClause parameter with dynamic sql.  The whereClause is not dynamic sql, it is a bunch of fields strung together with either AND or OR.  Those are the only two combining characters nettiers can handle when parsing a full string like that.

If you need greater than that level of complexity then try using the Find method and passing in a FilterParameterCollection.

Changing NetTiers auto generated sprocs on the server is always a bad idea, and could cause some pretty big issues for you.  If you want control over the sproc itself you need to create a custom sproc that nettiers can then wire to your object.  I do not believe custom sproc methods natively support paging in the way you are trying to do it though.

**Comment by jeremeguenther** [comment]
Should this issue be closed out?
