### ISSUE TITLE
Please help on this error ***SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.

### ISSUE THREAD

**Issue by ghost** [netTiers/netTiers#459]
I am evaluating CodeSmith ,netTiers to be able to buy it.
Support is one of my evaluation priorities.

I have downloaded a trial version and managed to create DLLs for one of or databases that has meny date fields with default value as "getDate()". However, when I don't pass this value in the vb.net code, the following error shows:

> **### SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.**

i.e In customer table I use following line to save a new customer:
 DataRepository.CustomerProvider.Save(c)

This customer table has a field named "DateCreated" which I put its default date as getDate() in the Customer table in SQL DefaultValueBinding.

However, codesmith dlls break in the save line showing the error in above.

When I put c.DateCreated= Today() in the code before the save line it doesn't throw error but I need this to be a default auto generated value from the SQL table by getdate() in the  DefaultValueBinding  as mentioned above.

Please help on the evaluation to be able to start with Codesmith.

Regards

**Comment by jeremeguenther** [comment]
CodeSmith and NetTiers are two separate things.  Other than this forum there is very little support for NetTiers itself, it is not a product actively developed by CodeSmith, it is more of a community project built around CodeSmith.

I have never personally used it, but it sounds like the setting CSPUseDefaultValForNonNullableTypes might be what you are looking for.  That would require you to use a custom stored procedure rather than the auto generated ones though.

NetTiers is not really setup to use default values in columns that I am aware of.  Your best option would be to create an extension method or something in .net and set the default value there.

**Comment by khaledEzzatAbdelgawad** [comment]
No I have some colleagues using codesmith and haven't experienced this issue with default value!!!

**Comment by jeremeguenther** [comment]
Do your colleagues use NetTiers?

The default value feature you are looking for has very little to do with CodeSmith.  It is simply a result of how the NetTiers templates were created.

In order for a column's default value to be used, that column needs to be excluded in the update statement.  I am not aware of any setting in the NetTiers templates that would allow you to ignore all non-nullable columns, or any other columns for that matter in an update statement.

**Comment by khaledEzzatAbdelgawad** [comment]
Well, they showed me this working at their side and yes they use ,netTiers

**Comment by jeremeguenther** [comment]
I would love to see their code if they are using the built-in NetTiers save methods.

I have only been able to accomplish this by using custom stored procedures.  Which are of course called via NetTiers, but I still have to write the procedure.

**Comment by jeremeguenther** [comment]
Something else I ended up doing was standardizing my DB so all the tables that needed them had the same column names for datecreated or dateupdated.  I then wrote a nettiers extension that used reflection to find these names and set them based on whether the object was new or dirty, etc before I actually saved the object.

**Comment by niemyjski** [comment]
It would be helpful to attach a small sql script that will recreate the minimal database (tables) that will recreate this and note any template settings that you changed (from the defaults).

**Comment by jeremeguenther** [comment]
@niemyjski what is the "this" you are referring to?  My date setup, @khaledEzzatAbdelgawad 's issue with his dates blowing up, or his colleagues code that sounds like it does what he wants?

**Comment by niemyjski** [comment]
good point, I was referring to his issue. Perhaps we need to update the issue templates and close any issue that doesn't have a sample that reproduces it. too little resources to investigate what we think the issue is.

**Comment by jeremeguenther** [comment]
Or at least prioritize things in that manner.
In this particular case, I have seen the issue being discussed.  However, I would call this a feature request rather than an issue or bug.  And how would you solve the issue that .net allows for Min dates older than sql does?

If I were to "fix" this issue, I think I would end up creating a setting that allows for the build-in validation to check for this and/or a setting to auto adjust the min dates upwards.

**Comment by moto-geek** [comment]
I typically ALLOW NULL [on] on my DateTime database fields. Then if there is no date provide, I pass a "null" value and it won't complain then. But if ALLOW NULL [off] is not allowed, yes the net tiers will expect a valid date value.  Hope that helps.
