### ISSUE TITLE
General nettiers practices

### ISSUE THREAD

**Issue by jamilhaddadin** [netTiers/netTiers#460]
Is there any resources talking about general nettiers best practices & common mistakes? (Like intensive use of deepload & other areas)
I am reviewing a code for a company who are running the default template of nettiers and i am seeing many critical, high & medium finding (FxCop & other tools), I think it worth visiting this area by the team

**Comment by jeremeguenther** [comment]
By far the biggest mistake I have seen was a company that allowed two developers to generate two different instance of NetTiers based on two different configs and merge them together in the same set of NetTiers folders.

That meant that going forward they were no longer able to auto generate their entire Data Access Layer, they had to manually copy in changed files individually.  Particularly when over time they lost one of the original configs, and forgot which files had been generated by which config.

It would probably be a good idea to have the config checked into source control so it is never lost.

**Comment by jeremeguenther** [comment]
Another mistake I have seen made is putting data access calls inside of a loop.  I did not mention this before because it is really a generic mistake that is not specific to NetTiers.

When a developer does not understand what a data access layer is, and makes 100 calls to the database inside of a loop instead of a single call grabbing 100 records outside of the loop, performance takes a huge hit.
