### ISSUE TITLE
Web Services Library Issues

### ISSUE THREAD

**Issue by Conquerence** [netTiers/netTiers#463]
I have been using .netTiers as the ORM framework for my WinForms application since 2007.  I am very comfortable with .netTiers and happy with the features and performance.  I am now looking to port my application to the web, and so I need to create a webservice data api.

I attempted to use the .netTiers webservice templates to add to my existing .netTiers components.  However, the resulting code gives me a number of build errors that I am not understanding.  The first error indicates that there is a missing file:

Error	CS2001	Source file '[...]\NetTiers\Conquerence.Data.WebServiceClient\Web References\WsProxy\Reference.cs' could not be found.

I can't find any documentation on what the References.cs file is supposed to be or why it did not generate, etc.  Can you give me any guidance in that regard?

The second group of errors occurs for every entity I have in the codebase in the datasource controls of the Web assembly.  Below is one example of the build error:

Error	CS0311	The type 'Conquerence.Web.Data.FlowProperty' cannot be used as type parameter 'Entity' in the generic type or method 'ProviderDataSource<Entity, EntityKey>'. There is no implicit reference conversion from 'Conquerence.Web.Data.FlowProperty' to 'Conquerence.Entities.IEntityId<Conquerence.Entities.FlowPropertyKey>'.	Conquerence.Web	[...]\NetTiers\Conquerence.Web\DataSourceControls\FlowPropertyDataSource.cs

Again, I cannot find any documentation that might guide me on how to adjust the settings when generating the Web section to avoid this build error.

Any help is appreciated.

**Comment by jeremeguenther** [comment]
I have noticed that there are features in the NetTiers templates that have not been updated for the newer versions of .net.  UnitTests being one example.  If no one is using them and keeps them updated then they no longer work with the latest versions of .net.

Also, there are certain config combinations that do not work.  It is very difficult in code to make sure every possible combination generates code that compiles.  I have asked CodeSmith to include a feature that allows us to make configurations a little more tightly coupled to each other so dependencies could be formed; which would help with this issue.  However, I do not think it is on their radar.

I have never seen your issue.  I am not using NetTiers as a service layer, just a regular data access layer for my website.  However, if you are using the latest version of NetTiers and if you upload your NetTiers.csp file then I can try doing a build and see if anything stands out to me.

Documentation for this project is definitely lacking.  I would love to work on it, however CodeSmith has said that can only be done via pull requests, which is way more effort and time then I have at the moment.  Maybe someday they will open up a normal wiki that we can edit via the web.

**Comment by Conquerence** [comment]
Here is my CSP file.  I was also going to ask about the unit tests, but it seems that they are not supported now?

[Conquerence.zip](https://github.com/netTiers/netTiers/files/2055066/Conquerence.zip)

**Comment by jeremeguenther** [comment]
I'll look at that as soon as I get a chance.

The templates are supported primarily by the community, not CodeSmith.  And currently I am the only one in the community I have seen doing any work on them.  If you have the time it would be great to have someone else submitting pull requests with updates.

The Unit Tests just need to be updated with some of the modern decoration or perhaps have some name change alterations.  I do not use them currently, so I have not updated that portion of the templates.

**Comment by Conquerence** [comment]
Here is the CSP file again. 

[Conquerence.zip](https://github.com/netTiers/netTiers/files/2055179/Conquerence.zip)

**Comment by jeremeguenther** [comment]
Ok, looking over the code here is what it looks like to me.

NetTiers primary purpose was as a data access layer.  However, as the movement to create disconnected architectures took hold back before 2013 and even up to 2013 a few people were working on setting up NetTiers so that it could generate two halves of a SOAP web service.

So you have the traditional data access layer, which is exposed using the asmx file in the WebServices folder.  You then have to get that site up and running so that the next NetTiers generation can run two Visual Studio utilities "wsdl" and "disco".  These are generated through the method CreateWebServiceProxies which does not look like it was ever officially wired up, probably because it takes several steps to make that part actually work correctly.  These tools then generate that missing file Reference.cs which is the web service connection between the exposed .asmx service and all the WebServiceClient files.  The goal then is for these files to be run as the data access connection for the site itself.

It is a very disconnected architecture.  No one has bothered to update it to the newer service implementations, or enhance that method for the more current generation tools.  My guess is because this is such an advanced design that the majority of people will not be using it.  And for those who do need such a feature they are going to be well versed in the NetTiers templates and would not have a need for the last few finishing connectivity features that would allow the general public to use it without much knowledge of the templates.

// Generating webreference for visual studio
// 1. wsdl /out:c:\Web References\WsProxy\Reference.cs http://commerce.services/CustomerServices.asmx?WSDL
// 2. disco /out:c:\Web References\WsProxy\ http://commerce.services/CustomerServices.asmx

So my question to you is, do you really need this architecture?  Why are you trying to design your site in this disconnected manner?

**Comment by Conquerence** [comment]
Thanks for looking into this for me.

To answer the question: "So my question to you is, do you really need this architecture? Why are you trying to design your site in this disconnected manner?"

I don't.

I have an existing WinForms application that I want to port over to a web application.  As the first step in that process, I need to design a REST API for data access to the new web based UI that I wish to develop.  However, I don't want to lose any of the functionality of my existing back end, which is all coded against the netTiers ORM.  My original thought was that I would use ASP.NET Web API 2 to design a REST API with my existing netTiers libraries supplying the entities and DAL, but as I started to explore the process, I found myself wishing that I could generate this layer.  I remembered from way back when that netTiers did have some sort of data access web service component, and I thought that I would take a look at it to see if it would save me some time.  I really did not know anything about they netTiers web service layer, other than it existed, and two days ago was the first time I tried to generate it.  I probably should have looked more closely at the code before trying to get it to build, I might have then realized that the web service layer was a SOAP API, rather than a REST API, which is what I am looking for.  It also seems that the web service layer has been abandoned, essentially.

I suppose I will go back to coding a ASP.NET Web API 2 layer on top of my netTiers libraries.  I may try to create some code generation templates to do that and to generate the unit tests for the API.

Thanks for your help.

**Comment by jeremeguenther** [comment]
Unless you are trying to do some pure javascript front end, I am still confused as to why a REST API is mandatory for this port.

Your existing nettiers dlls will work the same between the webforms application and the web application, the only thing that has to change is the config file.  You can use MVC and razor or webforms.  I use both with nettiers all the time.

It would not be all that difficult to copy the .asmx generation template and create a .svc generating template to serve up a REST front end.  The client templates would also need to be re-written though, that would take a bit more work.  It kind of sounds like you do not want to use the generated .net client though, so that approach could work for you.

**Comment by Conquerence** [comment]
I currently already have a site functioning on MVC and razor, which has a very small limited subset of the winforms functionality.  That site uses the netTiers ORM.  I originally explored the option of expanding that into a full blown port of the winforms app.  I was ultimately not satisfied with the results.  I am looking to expand my UI options, and to support the option to code native apps for iPhone, iPad, Android, etc.

At this point in the project lifecycle, I have a huge amount of backend functionality that I am very happy with, with a horribly out of date UI.  I am looking at a good REST API as the best long term investment in expanding my options for UI development.

I have started to add some user templates to the latest build to create a ASP.NET Rest API, so if you are interested in including that in a future .netTiers release, I'd be happy to share.

**Comment by jeremeguenther** [comment]
I never submit anything back to the nettiers code base until I have had it running in my production environments for a bit.

Once you have a stable solution built and have been using it in production for a bit, throw an option into the NetTiers.cst file to allow people to enable or disable the generation of the REST api and I would love to include it, or you could if you are comfortable using github.

Actually, given that a properly implemented rest api using WCF could support both SOAP and REST, it would be ideal to turn the "GenerateWebservice" checkbox into a dropdown that allows you to select None or ASMX or WCF.  Just in case people are still using the old version.

**Comment by jasona22** [comment]
So after reading the above, I think I understand that the Web Service functionality does not currently work out of the box?  I suppose I could just use netTiers to make a library and then build standard web services to consume it for my disconnected front end?  I am so not a web guy (web services included).  But the customer we have is implementing some changes requiring web services.  I'm not the designer here, just having to try to figure out how to turn my netTiers project into a disconnected web services solution.  Any suggestions?

**Comment by jeremeguenther** [comment]
Correct, to my knowledge there is no working out  of the box web service implementation for Nettiers, just a bunch of really old templates that get you the majority of the way there for an old SOAP implementation.  It would be really great if someone wanted to implement a more modern service feature in Nettiers.  If I ever have the need I will do it.

Currently I use database driven reflection to build a fairly flexible REST API on top of Nettiers and MVC.  You could go that route, or if you need a more powerful REST service then setup a full WCF implementation with Nettiers getting and saving the data for it.

**Comment by jasona22** [comment]
Are you at liberty to explain the " database driven reflection to build a
fairly flexible REST API"?  I like the sound of it, but I've been putting
my head to it a bit and not able to fully visualize what you are saying.
Is this a netTiers template set?  I could see writing an application that
parses the sys table/column tables and builds something. (kind of like what
Codesmith is doing)  But I am not sure I get the reflection part.

I had to look up REST API; I had no idea.  I think I get what its doing
(taking a string: aka URI, and using that as instructions to the server so
it returns the right object).  It is kind of a key/value pair of sorts.
Provide me a key and I will return you the value.  Based on the key, it can
return a collection or an individual element from the collection.  It can
even be nested k/v pairs where the value can take another key and return a
value from within.  key: "/customers/{customerId}/accounts/{accountId}"
would be an example of nested k/v.  Just the way my brain works I guess.
Of course, I get that it isn't stored like a key value pair in a structure
exactly.  Just the interface concept is similar.

I guess, while I am interrupting your Saturday, do you have any recommended
REST resources/examples?  Just trying to short circuit my googling time.
I'm currently on RestfulAPI.net.

Thanks, I appreciate you and your quick responses.

Jason

PS As an aside, I am concerned with codesmith longevity.  really useful
tool, but they don't support the templates, editing the templates is
frowned upon - unless you are submitting changes, and the community isn't
really supporting the templates and codesmith is not useful without the
templates.  Seems like a recipe for decay.  Almost seems like codesmith is
done with that and on to bigger and better things - Microsoft and
silverlight anyone?  Well, microsoft and lots of endeavors they get people
to buy-in to and then pull the plug on.  <sigh> </rantEnd>

**Comment by jeremeguenther** [comment]
If you are not familiar with web service integrations, you are going to need to spend a lot of time learning or hire someone for this project.  Generally speaking web services are a pretty basic idea that most developers understand, it will be hard to do much until you understand them.

At their most basic:
REST = Exchanging information in JSON format over the HTTP protocol
SOAP = Exchanging information in XML format over the HTTP protocol

I have built a poor mans REST API by creating an ApiController in MVC with a Save method, that takes a string id as a parameter.
you call it like http://www.domain.com/api/save/endpointname

The save method then uses a database table to look up a Nettiers object and a list of fields associated with that endpoint name.  Using reflection I create an instance of that object, de-serialize the incoming data into a Dictionary<string,string> and apply all the resulting data to the properties of the newly created object, then save the object to the database.

Reflection comes into play because Nettiers enforces standards in its generation.  For example the service object to save an object always ends with the word "Service".  Every property has getters and setters, so they can be accessed the same way every time.

The Codesmith company is primarily focused on their Exceptionless product these days from what I can tell.  However, they do maintain the Generator product and make sure it continues to work with database versions as they come out.

Template support and maintenance is definitely community driven, and the Nettiers community has gotten pretty small since Microsoft's Entity Framework finally became a viable product.  I personally still prefer Nettiers over EF because of the standards it promotes and enforces, and because it works so well with a database first approach; and because reflection works so well with it.

However, you are right, there is no big company driving the Nettiers templates forward at the moment.  You can edit the templates all you want, that is what they are there for.  The only reason not to is if you want to more easily get any changes the community submits for use in your projects.  However, there is a feature built into nettiers to create your own supplemental templates in a way that does not affect the core templates and render them un-upgradable.  I use that feature quite a bit.

**Comment by jeremeguenther** [comment]
Some day, if I have time, I would very much like to create a full WCF REST API system built into Nettiers.  However, that is going to take a lot of thought in how to keep it flexible.  And I have not had the time.

**Comment by jasona22** [comment]
That wcf idea sounds super powerful.  Is it ready yet?  How about now?
Now?  ;)


I appreciate the insight and info.  I see wcf possibly sitting on my
nettiers library in my future.

Jason

**Comment by jeremeguenther** [comment]
I have never used csla.  However I do not think netTiers has any options built-in that would allow something like that without modifying the templates.  You would either have to create some custom user templates in the UserLib folder, or add it as a new feature into the main templates.

But yes, that is essentially the idea I was thinking of.  Adding the ability to generate some sort of WCF wrapper for select tables and views.

**Comment by jasona22** [comment]
So I've created a small tool using the Roslyn compiler to extract my
methods.  It builds interface and wrapper methods.   It's crude/brute
Force, but mostly works.

In your version of wrapper, are you mainly just wrapping the dataProvider
properties?  Thus your existing consumer would just reference the
dataProviderService.myObject.GetAll() instead of the non service wrapper?

**Comment by jeremeguenther** [comment]
No, my wrapper is pretty limited.  It only accepts a key/value list of items.  It uses a database table to map the keys to various objects and properties.  And it uses reflection to load those objects and apply the value to the properties.  Then it uses reflection to call the correct Save method for each object.

That's it at a basic level. In practice that mapping table has a lot of flags on it that allows me to manipulate the data coming in.  And my save method is pretty complicated and capable of identifying the correct order to save the objects in and applying foreign key values as needed; all using reflection and nettiers deepload attributes.

I never expose any of the nettiers objects or attributes directly.  The mapping table is used to translate values for all of it.  That's both it's biggest obfuscating security feature, and greatest weakness in terms of functionality.
