### ISSUE TITLE
Hooks 

### ISSUE THREAD

**Issue by jasona22** [netTiers/netTiers#466]
I am still unsure if this is to be used as a forum type question area.  This feels more like bug reporting.  Please guide me to regular question area if I am in the wrong place.

So, after some misunderstanding, I've un-edited my template and I'm back on stock net-tiers.  After years of editing CSLA templates for a very custom setup, this feels odd, but  I'm learning.

On to my question.  I see the OnPropertyChanged hooks and get how to use them.  What I don't see is a similar thing for the child collections on my object.  What I am looking for is where to reference a child objects OnPropertyChange(ed/ing) handlers so I can notify the parent of a child changing -- adding a parent handler to a child's event.  It would seem the BO would be a better place than the "code behind" of a form.  I am sure its here somewhere, but I just do not readily see it.

Thanks in advance for your wisdom and guidance.

**Comment by jeremeguenther** [comment]
Stack overflow with the nettiers tag is another option.

I have never used the event hooks, I'll look and see if what you are looking for exists when I get back in front of my computer.

**Comment by jasona22** [comment]
Perhaps I am.  I was thinking that "netTiers" was a take on n-tier tech.
Thus I use the "entities", named after my tables, as containers for data
and lists of objects and bind them to my UI elements for a user to
view/edit.

For the specific question I had, I can use the OnPropertyChange event of a
child to notify the parent object when a property changed.  Such as an
order is closed or canceled.  However, I cannot find a smooth location to
tell the parent to "add handler" for the event.  The code behind of a form
seems like an unruly place.  Ideally, there would be a "child load" method
on the parent object somewhere that the parent object can wire up those
handlers and maybe even an unload to unwire them.

I think my ignorance is showing.  What is the real difference in your
opinion of a business object and what netTiers does? Perhaps I am using the
term Business Object erroneously, but I think my usage of the objects are
as intended.  I mean, netTiers has events, validation rules and other such
things.  To me, they are business objects, but again, I may have a broad
and imprecise definition of Business Object.

My expected usage is to 1) CRUD data; 2) Layer a UI on top of objects
(business, data or whatever they are accurately called) to provide a
mechanism for the user to act upon the data.  Anything beyond that is only
for the facilitating of 1 and 2 (mostly 2) as 1 is pretty well handled.

My apologies for any misuse of terms.  I do not mean to cause confusion.  I
am just trying to figure out where to properly perform actions in this
architecture.  Again, for this specific situation, how to get notified at
the parent level when the property value on a child  changes.

Jason

**Comment by jeremeguenther** [comment]
I suppose you could call them business objects.  I just do not call it a business logic layer.  I have written a custom business object layer that works with nettiers objects for most of my more detailed custom logic.  I do use straight nettiers for most of my data binding and other crud needs, just not for any form of decision tree logic which is what I typically call the business layer.  I am unsure what the official definitions in that are are.

If you wanted to add a feature to nettiers (and submit it back after testing) so that child objects could have references to their parents, and trigger event updates on them that would be wonderful.

In lieu of that, or perhaps has an intermediary step, you could try using the "Tag" attribute to set a parent reference on your child objects.  Then in your child event handlers you could reference this Tag and trigger the appropriate action on it.  I use the Tag object whenever I need to add something additional to my objects that is not in nettiers and that is too specific to a particular use case for me to add a feature into nettiers.
